name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar no EC2 e fazer deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/taca-das-casas-deploy

            echo "Atualizando código..."
            git pull origin main

            echo "Rebuildando containers..."
            docker compose up -d --build

            echo "Limpando imagens..."
            docker image prune -f

            echo "✅ Deploy concluído"